Finish profile page
heig-PDG/mono pull request #121
Opened 2020-11-22 10:04 UTC by GTZL1

2020-11-22 15:26 UTC, glsubri requested changes

2020-11-22 15:26 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/NavGraph.kt
> +    val profile: ()->Unit={
Fix formatting

2020-11-22 15:26 UTC, glsubri commented on src/mobile/src/main/res/values/profile.xml
> +</resources>
You should do the same thing I did:

Settings > Editor > General > Ensure an empty line at the end of a file on Save

In Android Studio

2020-11-22 15:26 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/NavGraph.kt
> +import androidx.compose.runtime.Composable
Should not be imported

2020-11-22 15:26 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/profile/Profile.kt
> +) {
`Profile` is a `Composable`, as such, it should have a `modifier`, as usual

2020-11-22 15:26 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/profile/Profile.kt
> +            )
Does not match Figma

2020-11-22 15:26 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/profile/Profile.kt
> +        }
Doesn't match Figma exactly, but I'm fine with it

2020-11-22 15:26 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/profile/Profile.kt
> +                    modifier = Modifier.size(96.dp).clip(CircleShape)
This should not show "thors" profile image, but a correct placeholder

2020-11-22 15:26 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/profile/Profile.kt
> +                    modifier = Modifier.size(96.dp).clip(CircleShape)
And format of `modifier` is all over the place

2020-11-22 15:26 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/profile/Profile.kt
> +                        text = stringResource(id = R.string.profile_editpic), fontSize = 7.sp
Should apparently be 10dp, not 7. Instead of defining it here, we could refer to a text style from the theme

2020-11-22 15:26 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/profile/Profile.kt
> +            placeholder = { Text(stringResource(id = R.string.profile_name_placeholder)) }
Even though, it is like the Figma prototype, I do not think this prototype accounted for the fact that the label would be in the center of the field when not selected.

My opinion is that we should remove the caps lock

2020-11-22 15:26 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/profile/Profile.kt
> +            value = "", onValueChange = {/*TODO do something with that*/ },
formatting

2020-11-22 21:16 UTC, alexandrepiveteau commented on src/mobile/src/main/java/tupperdate/android/profile/Profile.kt
> +    //it's funny to have Thor as default image, isnt'it ?
No

2020-11-23 08:15 UTC, alexandrepiveteau commented on src/mobile/src/main/java/tupperdate/android/profile/Profile.kt
> +            onClick = { onSaveClick() },
```suggestion
            onClick = onSaveClick,
```

2020-11-23 08:15 UTC, alexandrepiveteau commented on src/mobile/src/main/java/tupperdate/android/profile/Profile.kt
> +            onClick = { onSignOutClick() },
```suggestion
            onClick = onSignOutClick,
```

2020-11-23 08:15 UTC, alexandrepiveteau commented on src/mobile/src/main/java/tupperdate/android/profile/Profile.kt
> +fun ProfilePreview() {
```suggestion
private fun ProfilePreview() {
```

2020-11-23 09:07 UTC, glsubri submitted a review, later dismissed

2020-11-23 09:15 UTC, glsubri approved these changes

2020-11-23 09:25 UTC, merged