Profile general page
heig-PDG/mono pull request #175
Opened 2020-12-22 17:17 UTC by GTZL1

2020-12-24 10:51 UTC, alexandrepiveteau submitted a review, later dismissed

2020-12-24 10:51 UTC, alexandrepiveteau commented on src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileGeneral.kt
> +                modifier = Modifier.width((recipeCardWidth * 0.8).dp)
Eventually `fillMaxWidth(0.8)` (the variant which takes a percentage as a parameter). But I'm not sure you'd really want that, you probably should use a padding instead.

2020-12-24 10:51 UTC, alexandrepiveteau commented on src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileGeneral.kt
> +private const val recipeCardHeight = 160
Please use some `Dp` rather than some `Int` here, and use PascalCase rather than camelCase.

2020-12-24 10:51 UTC, alexandrepiveteau commented on src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileGeneral.kt
> +) {
Missing a `Modifier` parameter.

2020-12-24 10:51 UTC, alexandrepiveteau commented on src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileGeneral.kt
> +            .padding(end = 16.dp),
It's very weird to have the Composable set the padding itself, rather than its caller / parent. This requires the Modifier parameter.

2020-12-24 10:51 UTC, alexandrepiveteau commented on src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileGeneral.kt
> +    userRecipes: List<RecipeApi.Recipe>,
This is deprecated. Please use the new Recipe class from data instead.

2020-12-29 08:05 UTC, glsubri requested changes

2020-12-29 08:05 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileGeneral.kt
> +private const val RecipeCardHeight = 160
As said by @alexandrepiveteau, theses should be `dp` and not `int`

2020-12-29 08:06 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileGeneral.kt
> +    //TODO add the new appbar done by G-L for the new navigation
The appbar will not be displayed here. You can check out the code in `Home.kt` to see how it is done.

2021-01-02 10:00 UTC, glsubri reviewed
Very nice. It looks very good and it's virtually the same as the Figma prototype. Good job on that one!

I have noted a few mistypes. Instead of the `MaterialTheme` typography, we should use our own. I've provided them as suggestions. 

:+1:

2021-01-02 10:00 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileGeneral.kt
> +            style = MaterialTheme.typography.overline
```suggestion
            style = TupperdateTypography.overline
```

2021-01-02 10:00 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileGeneral.kt
> +            style = MaterialTheme.typography.overline
```suggestion
            style = TupperdateTypography.overline
```

2021-01-02 10:00 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileGeneral.kt
> +            Text(text = name, style = MaterialTheme.typography.subtitle1)
```suggestion
            Text(text = name, style = TupperdateTypography.subtitle1, color = Color(0f, 0f, 0f, 0.6f))
```

2021-01-02 10:00 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileGeneral.kt
> +            Text(text = email, style = MaterialTheme.typography.subtitle2)
```suggestion
            Text(text = email, style = TupperdateTypography.subtitle2, color = Color(0f, 0f, 0f, 0.3f))
```

2021-01-02 10:00 UTC, glsubri commented on src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileGeneral.kt
> +                    style = MaterialTheme.typography.caption,
```suggestion
                    style = TupperdateTypography.caption,
```

2021-01-02 10:06 UTC, glsubri submitted a review, later dismissed

2021-01-02 10:11 UTC, glsubri approved these changes

2021-01-02 10:18 UTC, merged